// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkgorxvkwdkxvvjhupyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrZ29yeHZrd2RreHZ2amh1cHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzI3MzcsImV4cCI6MjA2MDcwODczN30.Ox7cuQ1c6-qKBReo38QU5_mvDfhcKullO82yRvmC78o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);